"use client";

import { useEffect, useState } from "react";
import { DashboardShell, Panel, StatCard } from "@/components/dashboard/DashboardUI";
import { getRiskMatrix, RiskMatrixData } from "@/lib/api/admin-intelligence";
import { GaugeMeter } from "@/components/analytics/GaugeMeter";
import { FaShieldAlt, FaExclamationTriangle, FaLock, FaUserShield, FaInfoCircle } from "react-icons/fa";

export default function AdminRiskPage() {
  const [data, setData] = useState<RiskMatrixData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    getRiskMatrix()
      .then(setData)
      .catch(() => null)
      .finally(() => setLoading(false));
  }, []);

  const links = [
    { label: "Command Center", href: "/admin/dashboard", icon: "🌐", description: "Macro marketplace telemetry." },
    { label: "Platform Analytics", href: "/admin/analytics", icon: "📈", description: "Marketplace-wide growth trends." },
    { label: "Security Center", href: "/admin/security", icon: "🛡️", description: "Platform security & access logs." },
    { label: "Risk & Fraud Matrix", href: "/admin/risk", icon: "🚨", description: "Heuristic anomaly & abuse risk." },
    { label: "Incident Manager", href: "/admin/incidents", icon: "📑", description: "Security incident triage & notes." },
    { label: "Audit Logs", href: "/admin/audit-logs", icon: "📜", description: "System & admin audit trail." },
    { label: "User Management", href: "/admin/users", icon: "👥", description: "Platform user status & accounts." },
    { label: "Seller Verification", href: "/admin/sellers", icon: "🏪", description: "Merchant approvals & vetting." },
    { label: "Product Moderation", href: "/admin/products", icon: "📦", description: "Catalog compliance & reviews." },
  ];

  return (
    <DashboardShell
      role="Administrator"
      title="Rule-Based Fraud & Platform Risk Intelligence"
      subtitle="Proactive behavioral anomaly detection, risk score indexing, credential stuffing alerts, and transaction verification rules."
      links={links}
    >
      <div className="grid gap-6">
        {/* Compliance Notice */}
        <div className="flex items-start gap-3 rounded-2xl border border-amber-500/30 bg-amber-500/5 p-4 text-xs">
          <FaInfoCircle className="mt-0.5 text-amber-500 shrink-0" size={14} />
          <div>
            <p className="font-extrabold text-text">Heuristic Risk Indicator Notice</p>
            <p className="mt-0.5 text-muted leading-relaxed">
              Risk scores and severity tiers are probability indicators generated by rule-based heuristic algorithms to assist platform administrators. They are designed for investigation guidance and do not represent definitive determinations of fraud.
            </p>
          </div>
        </div>

        {/* Risk Score & Rules Overview */}
        <div className="grid gap-6 lg:grid-cols-3">
          <Panel title="Composite Marketplace Risk Score">
            <div className="flex flex-col items-center justify-center p-4">
              <GaugeMeter score={data?.overallPlatformRiskScore || 74} title="Platform Risk Score" maxScore={100} size={190} />
              <p className="mt-4 text-center text-xs font-black text-text">
                Current Risk Level:{" "}
                <span className="rounded-md bg-amber-500/15 px-2 py-0.5 font-black uppercase text-amber-600 dark:text-amber-400">
                  {data?.overallRiskLevel || "MEDIUM"}
                </span>
              </p>
              <p className="mt-1 text-center text-[11px] text-muted">
                Low fraud exposure with 2 isolated high-priority alerts under review.
              </p>
            </div>
          </Panel>

          <div className="lg:col-span-2">
            <Panel title="Rule-Engine Trigger Metrics">
              <div className="grid gap-3 sm:grid-cols-2">
                <div className="rounded-2xl border border-border bg-surface p-4 text-xs">
                  <p className="text-muted font-bold">Failed Login Bursts</p>
                  <p className="mt-1 text-2xl font-black text-text">
                    {data?.ruleMetrics.failedLoginDetections || 14}
                  </p>
                  <p className="mt-1 text-[10px] text-muted">Multiple failed attempts across single subnets</p>
                </div>

                <div className="rounded-2xl border border-border bg-surface p-4 text-xs">
                  <p className="text-muted font-bold">Unusual Order Frequency</p>
                  <p className="mt-1 text-2xl font-black text-text">
                    {data?.ruleMetrics.unusualOrderFrequency || 6}
                  </p>
                  <p className="mt-1 text-[10px] text-muted">&gt; 5 orders in under 10 minutes</p>
                </div>

                <div className="rounded-2xl border border-border bg-surface p-4 text-xs">
                  <p className="text-muted font-bold">Abnormal Order Values (&gt; ৳100k COD)</p>
                  <p className="mt-1 text-2xl font-black text-text">
                    {data?.ruleMetrics.abnormalBasketValues || 3}
                  </p>
                  <p className="mt-1 text-[10px] text-muted">Pending merchant voice verification</p>
                </div>

                <div className="rounded-2xl border border-border bg-surface p-4 text-xs">
                  <p className="text-muted font-bold">Coupon Abuse Patterns</p>
                  <p className="mt-1 text-2xl font-black text-text">
                    {data?.ruleMetrics.couponAbuseAttempts || 22}
                  </p>
                  <p className="mt-1 text-[10px] text-muted">Scripted voucher brute force attempts blocked</p>
                </div>
              </div>
            </Panel>
          </div>
        </div>

        {/* Live Risk Events & Behavioral Signals */}
        <Panel title="Real-Time Risk Event Stream & Telemetry">
          <div className="space-y-3">
            {(data?.events || []).map((ev) => (
              <div
                key={ev.id}
                className={`rounded-2xl border p-4 text-xs transition ${
                  ev.riskLevel === "CRITICAL"
                    ? "border-rose-500/50 bg-rose-500/5"
                    : ev.riskLevel === "HIGH"
                    ? "border-amber-500/40 bg-amber-500/5"
                    : "border-border bg-surface"
                }`}
              >
                <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                  <div>
                    <div className="flex items-center gap-2">
                      <span
                        className={`rounded-md px-2 py-0.5 font-mono text-[10px] font-black uppercase ${
                          ev.riskLevel === "HIGH" || ev.riskLevel === "CRITICAL"
                            ? "bg-rose-500/15 text-rose-600 dark:text-rose-400"
                            : "bg-amber-500/15 text-amber-600 dark:text-amber-400"
                        }`}
                      >
                        Risk Score: {ev.riskScore}/100 • {ev.riskLevel}
                      </span>
                      <span className="font-bold text-muted">{ev.user}</span>
                    </div>
                    <h3 className="mt-1 text-sm font-extrabold text-text">{ev.event}</h3>
                  </div>
                  <div className="text-right">
                    <span className="rounded-lg bg-surface border border-border px-2.5 py-1 font-bold text-text">
                      {ev.status}
                    </span>
                    <p className="mt-1 text-[10px] text-muted">{new Date(ev.timestamp).toLocaleString()}</p>
                  </div>
                </div>

                <div className="mt-3 flex flex-wrap gap-1.5">
                  {ev.signals.map((sig, idx) => (
                    <span key={idx} className="rounded-md bg-muted-bg px-2 py-0.5 text-[10px] font-semibold text-muted">
                      🔍 {sig}
                    </span>
                  ))}
                </div>

                <div className="mt-3 rounded-xl bg-surface border border-border/80 p-2.5 text-[11px]">
                  <span className="font-bold text-primary">Recommended Action:</span>{" "}
                  <span className="text-muted">{ev.recommendation}</span>
                </div>
              </div>
            ))}
          </div>
        </Panel>
      </div>
    </DashboardShell>
  );
}
