import { Store, Zap, Sparkles, Award, ShieldCheck, PackageCheck, TrendingUp, Clock } from "lucide-react";
import { Seller, SellerCategoryTab, TrustMetric } from "./seller.types";

export const CATEGORY_TABS: SellerCategoryTab[] = [
  { id: "all", label: "All Top Stores", icon: Store },
  { id: "electronics", label: "Electronics & Tech", icon: Zap },
  { id: "fashion", label: "Fashion & Lifestyle", icon: Sparkles },
  { id: "home", label: "Home & Living", icon: Award },
];

export const SELLERS: Seller[] = [
  {
    id: "nova-tech",
    name: "Nova Tech Official",
    category: "Consumer Electronics",
    categorySlug: "electronics",
    tagline: "Next-gen audio, smart accessories & high-speed chargers.",
    rating: 4.9,
    reviewsCount: "2.4k",
    sales: "14.8k+",
    positiveRate: "99.4%",
    responseTime: "< 25 min",
    initials: "NT",
    badge: "Top Tech Brand",
    badgeColor: "bg-indigo-500/15 text-indigo-600 dark:text-indigo-400 border-indigo-500/20",
    accentColor: "var(--color-primary)",
    gradient: "from-indigo-500 via-blue-600 to-purple-600",
    glowColor: "rgba(99, 102, 241, 0.25)",
    featuredTags: ["Active ANC", "GaN Chargers", "Wireless Audio"],
    isTopRated: true,
  },
  {
    id: "urban-loom",
    name: "Urban Loom Studio",
    category: "Apparel & Sustainable Fashion",
    categorySlug: "fashion",
    tagline: "Eco-crafted minimalist apparel, footwear & modern streetwear.",
    rating: 4.8,
    reviewsCount: "1.9k",
    sales: "9.5k+",
    positiveRate: "98.8%",
    responseTime: "< 45 min",
    initials: "UL",
    badge: "Eco Choice 2026",
    badgeColor: "bg-purple-500/15 text-purple-600 dark:text-purple-400 border-purple-500/20",
    accentColor: "var(--color-accent)",
    gradient: "from-purple-500 via-pink-500 to-rose-500",
    glowColor: "rgba(168, 85, 247, 0.25)",
    featuredTags: ["Organic Cotton", "Minimalist Cut", "Fast Shipping"],
    isTopRated: true,
  },
  {
    id: "home-aura",
    name: "HomeAura Living",
    category: "Interior & Artisan Decor",
    categorySlug: "home",
    tagline: "Modern aesthetics, ergonomic workspace essentials & artisan ceramics.",
    rating: 4.9,
    reviewsCount: "3.1k",
    sales: "12.2k+",
    positiveRate: "99.7%",
    responseTime: "< 30 min",
    initials: "HA",
    badge: "Design Award",
    badgeColor: "bg-amber-500/15 text-amber-600 dark:text-amber-400 border-amber-500/20",
    accentColor: "var(--color-warm)",
    gradient: "from-amber-500 via-orange-500 to-rose-500",
    glowColor: "rgba(249, 115, 22, 0.25)",
    featuredTags: ["Desk Setups", "Nordic Decor", "Handmade"],
    isTopRated: true,
  },
  {
    id: "aura-beauty",
    name: "Aura Skincare & Pure",
    category: "Beauty & Wellness",
    categorySlug: "fashion",
    tagline: "Clean, dermatologist-tested botanical serums and organic treatments.",
    rating: 4.9,
    reviewsCount: "1.6k",
    sales: "8.1k+",
    positiveRate: "99.2%",
    responseTime: "< 20 min",
    initials: "AB",
    badge: "Verified Pure",
    badgeColor: "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
    accentColor: "var(--color-success)",
    gradient: "from-emerald-500 via-teal-500 to-cyan-500",
    glowColor: "rgba(16, 185, 129, 0.25)",
    featuredTags: ["Cruelty-Free", "Bio-Active", "Zero Plastic"],
    isTopRated: false,
  },
  {
    id: "apex-gear",
    name: "Apex Velocity Gear",
    category: "Outdoor & High-Performance",
    categorySlug: "electronics",
    tagline: "Ultra-durable tactical gear, GPS trackers & smart outdoor wearables.",
    rating: 4.8,
    reviewsCount: "1.2k",
    sales: "6.4k+",
    positiveRate: "98.5%",
    responseTime: "< 1 hr",
    initials: "AV",
    badge: "Pro Grade",
    badgeColor: "bg-cyan-500/15 text-cyan-600 dark:text-cyan-400 border-cyan-500/20",
    accentColor: "var(--color-primary)",
    gradient: "from-cyan-500 via-blue-600 to-indigo-600",
    glowColor: "rgba(6, 182, 212, 0.25)",
    featuredTags: ["Waterproof", "Titanium Build", "2-Yr Warranty"],
    isTopRated: false,
  },
  {
    id: "zenith-crafts",
    name: "Zenith Artisan Lab",
    category: "Handcrafted & Leather Goods",
    categorySlug: "home",
    tagline: "Full-grain leather wallets, handcrafted desk mats & heirloom accessories.",
    rating: 4.9,
    reviewsCount: "2.8k",
    sales: "10.1k+",
    positiveRate: "99.6%",
    responseTime: "< 35 min",
    initials: "ZC",
    badge: "Master Artisan",
    badgeColor: "bg-rose-500/15 text-rose-600 dark:text-rose-400 border-rose-500/20",
    accentColor: "var(--color-warm)",
    gradient: "from-rose-500 via-red-500 to-amber-500",
    glowColor: "rgba(244, 63, 94, 0.25)",
    featuredTags: ["Full-Grain Leather", "Laser Engraved", "Lifetime Stitch"],
    isTopRated: true,
  },
  {
    id: "luna-ceramics",
    name: "Luna Craft Pottery",
    category: "Home & Handmade Tableware",
    categorySlug: "home",
    tagline: "Hand-thrown stoneware, ceramic vases & minimalist dinnerware sets.",
    rating: 4.9,
    reviewsCount: "2.1k",
    sales: "7.9k+",
    positiveRate: "99.5%",
    responseTime: "< 40 min",
    initials: "LC",
    badge: "Handmade Verified",
    badgeColor: "bg-amber-500/15 text-amber-600 dark:text-amber-400 border-amber-500/20",
    accentColor: "var(--color-warm)",
    gradient: "from-amber-400 via-orange-500 to-yellow-500",
    glowColor: "rgba(245, 158, 11, 0.25)",
    featuredTags: ["Dishwasher Safe", "Matte Glaze", "Artisan Made"],
    isTopRated: false,
  },
  {
    id: "soundpulse-audio",
    name: "SoundPulse Audio Lab",
    category: "Acoustics & Hi-Fi Gear",
    categorySlug: "electronics",
    tagline: "Studio monitor headphones, lossless DACs & acoustic soundbars.",
    rating: 4.9,
    reviewsCount: "3.4k",
    sales: "16.2k+",
    positiveRate: "99.8%",
    responseTime: "< 15 min",
    initials: "SP",
    badge: "Hi-Res Audio",
    badgeColor: "bg-indigo-500/15 text-indigo-600 dark:text-indigo-400 border-indigo-500/20",
    accentColor: "var(--color-primary)",
    gradient: "from-blue-600 via-indigo-600 to-violet-600",
    glowColor: "rgba(79, 70, 229, 0.25)",
    featuredTags: ["Lossless 24-bit", "Spatial Sound", "Fast Dispatch"],
    isTopRated: true,
  },
];

export const TRUST_METRICS: TrustMetric[] = [
  {
    icon: ShieldCheck,
    title: "100% Vetted Merchants",
    desc: "Rigorous identity & quality audit",
    color: "text-primary",
  },
  {
    icon: PackageCheck,
    title: "Guaranteed 48h Dispatch",
    desc: "Fast tracked warehouse fulfillment",
    color: "text-success",
  },
  {
    icon: TrendingUp,
    title: "99.4% Avg Satisfaction",
    desc: "Over 50,000+ happy buyers",
    color: "text-warning",
  },
  {
    icon: Clock,
    title: "24/7 Buyer Shield",
    desc: "Hassle-free 30-day refund policy",
    color: "text-accent",
  },
];
